baseURL = "https://example.com"
languageCode = "kr-ko"
title = "ecycle"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-131462075-1"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2019
    author = "Soonhwan.Lee"                           # Author's name
    avatar = "/images/ecycle.jpg"           # Author's avatar
    subtitle = "What I have to do. Good morning, Good evening, Good night."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "post" # post or other

    google_verification = ""
   
    description = "Project - make me better" # site description
    keywords = "development, programmer, dev, backend" # site keywords

    beian = ""
    baiduAnalytics = ""

[params.social]
    GitHub = "https://github.com/2cycle"
    Email   = "ecycle.hello@gmail.com"
    Instagram = "https://www.instagram.com/nawhnooseel"
    Facebook = "https://www.facebook.com/soonhwan.lee.37"
    Medium = "find"

